name: Ping and Trigger Selenium Workflow

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Keep GitHub repo alive (ping)
        run: echo "Pinging GitHub at $(date)"

      - name: Trigger Run Selenium Script workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 'selenium.yml'
          ref: 'main'
          inputs: '{"use_session_cache":"false","start_or_stop":"true"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
